[theme]                     # This header tells Streamlit you are defining theme settings
base="dark"                 # Choose the base theme: "dark" or "light"
primaryColor="#AF1763"      # Color for buttons, sliders, highlights
backgroundColor="#191C24"   # Background color of the main page
secondaryBackgroundColor="#202124ff"  # Background color of the sidebar
textColor="#babbb8ff"          # Default text color
font="sans serif"            # Font: "sans serif", "serif", or "monospace"
