[theme]                     # This header tells Streamlit you are defining theme settings
base="dark"                 # Choose the base theme: "dark" or "light"
primaryColor="#C2C5AA"      # Color for buttons, sliders, highlights
backgroundColor="#C2C5AA"   # Background color of the main page
secondaryBackgroundColor="#656D4A"  # Background color of the sidebar
textColor="#3F4137"          # Default text color
font="sans serif"            # Font: "sans serif", "serif", or "monospace"
